### ISSUE TITLE
Implement Pause State Ingame

### ISSUE THREAD

**Issue by KoroBli** [RobertFont/AlphaProject#11]
During the game the player must be allowed to pause and resume the game as pleased. Everything in the gameplay must stop and not recognise failure clicks.

**EXPECTED RESULT:**

_A method that stops the updates of the scripts, in the [InputManager.cs](https://github.com/RobertFont/AlphaProject/blob/master/Assets/Scripts/General/InputManager.cs)._

        public void TogglePause()
        {
            if(!paused)
            {
                pauseSystem.SetActive(true);
                construcionUI.SetActive(false);
                Time.timeScale = 0.0f;
                paused = true;
            }
            else if(paused)
            {
                pauseSystem.SetActive(false);
                construcionUI.SetActive(true);
                Time.timeScale = 1.0f;
                paused = false;
            }
        }

**Comment by Adri102** [comment]
Implemented in commit https://github.com/RobertFont/AlphaProject/commit/5e833967d6c2b74a36537b0a1065f0205250af45
