### ISSUE TITLE
Implement a custom cursor

### ISSUE THREAD

**Issue by KoroBli** [RobertFont/AlphaProject#13]
Change cursor icon to our own texture. The cursor must be full operative and detect properly the clicks. The texture shouldn't interfere with the gameplay or disrupt the immersion of the game.

**EXPECTED RESULT:**

_A texture that fits perfectly with the windows cursor._

**Comment by RobertFont** [comment]
Implemented in commit 7c554469728d19bd470b5bb8ea6aa3a8b14f87dc
