### ISSUE TITLE
Create Basic Events For The Gameplay

### ISSUE THREAD

**Issue by KoroBli** [RobertFont/AlphaProject#17]
Implant the basic events that will happen randomly during the gameplay, be sure that they work and happen when wanted to. It needs a canvas to write the descrtiption, an icon, and a sound.

**EXPECTED RESULT:**

_An [event manager](https://github.com/RobertFont/AlphaProject/blob/master/Assets/Scripts/Events/EventBehaviour.cs) that creates all the events randomly during the gameplay._

**Comment by KoroBli** [comment]
Duplicated, closing this issue.

**Comment by Adri102** [comment]
Done in issue #46
