### ISSUE TITLE
Create Level Design Map (The Layout of the map)

### ISSUE THREAD

**Issue by CristianLuzon** [RobertFont/AlphaProject#19]
Design the layout of the map, with all the information regarding the choices that the player has when it comes to placing their first base.

**EXPECTED RESULTS:**

_A .png, [LevelDesingMap](https://github.com/RobertFont/AlphaProject/blob/master/WikiResources/LevelDesingMap.png), that reflects the final layout of the game. Showing the placement of the resources in the map and the different locations where the player can start._

**Comment by Adri102** [comment]
Implemented in the commit https://github.com/RobertFont/AlphaProject/commit/1105ed0a21f294fa2ce2fd1b1b0ed1444db6b66b
