### ISSUE TITLE
Raycast To Place/Select Buildings

### ISSUE THREAD

**Issue by KoroBli** [RobertFont/AlphaProject#2]
Use raycast to mesure the distance between the camera and the terrain. The building must follow the mouse perfectly. It has to collide with buildings and terrain.

**EXPECTED RESULT:**

_A [script](https://github.com/RobertFont/AlphaProject/blob/master/Assets/Scripts/General/RaycastMouseController.cs) that generates raycast that collides with diferent tags, when constructing with terrain tag, and when selecting, with built tag._

**Comment by KoroBli** [comment]
Already done but with some bugs in the build

**Comment by Adri102** [comment]
Implemented in commit https://github.com/RobertFont/AlphaProject/commit/9a2a489613e4b1e59335c6bd1677d5bee2abef4c
