### ISSUE TITLE
Create The Thumbnails Of Ingame Props

### ISSUE THREAD

**Issue by CristianLuzon** [RobertFont/AlphaProject#20]
Draw a minimum of 12 thumbnails of the props that will be implemented in the game.

The props must include:

- Nature
- Pieces of wood and other materials
- Equipment
- Bridges

**EXPECTED RESULT:**

_An image that shows a total of 12 props, this image must include those props that are already developed and some others that will be implemented in the future._

**Comment by RobertFont** [comment]
Implemented in commit 92a321289065ad3d70e6d4770ea5b38827b2e41c
