### ISSUE TITLE
Create The Thumbnails Of Ingame Buildings

### ISSUE THREAD

**Issue by CristianLuzon** [RobertFont/AlphaProject#21]
Draw a minimum of 12 building ![thumbnails ](https://github.com/RobertFont/AlphaProject/blob/master/ConceptArt/2DThumbnailProps.png) for the game. This image must include:

**EXPECTED RESULT:**

_An image that shows a total of 12 buildings, this image must include those buildings that are already developed and some others that will be implemented in the future._

**Comment by RobertFont** [comment]
Job done, (added 12 prop thumbnails in the concept art folder).
