### ISSUE TITLE
Create The Size Chart Of The Buildings

### ISSUE THREAD

**Issue by CristianLuzon** [RobertFont/AlphaProject#22]
Create the Size Chart that compares and shows the different sizes of several buildings. 
TownHall, Lumber Mill, and House must be present.
This must be shown inside a single image.

**EXPECTED RESULT:**

_A png image that shows the size of the differents buildings that are implemented in the game._

**Comment by RobertFont** [comment]
Implemented in commit https://github.com/RobertFont/AlphaProject/commit/92a321289065ad3d70e6d4770ea5b38827b2e41c
