### ISSUE TITLE
Create The Size Chart For The Props

### ISSUE THREAD

**Issue by CristianLuzon** [RobertFont/AlphaProject#23]
Create the Size Chart that compares and shows the different sizes of all the current props. 
This must be shown inside a single image.

**EXPECTED RESULT:**

_A png image that shows the size of the differents props that are implemented in the game._

**Comment by RobertFont** [comment]
Implemented in commit https://github.com/RobertFont/AlphaProject/commit/92a321289065ad3d70e6d4770ea5b38827b2e41c
