### ISSUE TITLE
Create Level Flow Map (The Tech Tree)

### ISSUE THREAD

**Issue by CristianLuzon** [RobertFont/AlphaProject#24]
Create de level flow map with all the possibilities that the player has. This means to develop the tech tree of the game, showing all the options that the player has and requirements that some of these buildings have.

**EXPECTED RESULT:**

_A png image that shows all the options that the player has plus all the requirements that some of the buildings need in order to be constructed. The image must be clear and informative._

[FlowMap]( https://github.com/RobertFont/AlphaProject/blob/e00324a7e25685436b9e98c3162441eae3f72c7c/WikiResources/LevelFlowMap.png)

[TechTree]( https://github.com/RobertFont/AlphaProject/blob/e00324a7e25685436b9e98c3162441eae3f72c7c/WikiResources/TechTree.png)

**Comment by RobertFont** [comment]
Implemented in commit: https://github.com/RobertFont/AlphaProject/commit/e00324a7e25685436b9e98c3162441eae3f72c7c
