### ISSUE TITLE
Update the Screen Mockups

### ISSUE THREAD

**Issue by CristianLuzon** [RobertFont/AlphaProject#25]
Update the diferents game's mockups that we already have and improve their quality as well as create the ending screen of the game.

- [ ] Menu
- [ ] Settings menu
- [ ] Gameplay
- [ ] Ending

**EXPECTED RESULT:**

_The objective is to have all the old Mockups updated and improved to show a more accurate representation of how the final game should look like._

**Comment by RobertFont** [comment]
Implemented in commit 5141e2713a9d2fdde6c0c586a56dbf25f9b0ab1e

**Comment by RobertFont** [comment]
Implemented in commit 51346f9b340b72ded0a8faabf9a0ce4807128f6e
