### ISSUE TITLE
Implement Scene Transition Animation

### ISSUE THREAD

**Issue by CristianLuzon** [RobertFont/AlphaProject#26]
Add an animation transition to all the scenes in Unity, probably a fade in and fade out between the screens in the game.

**EXPECTED RESULT:**

_A [script](https://github.com/RobertFont/AlphaProject/blob/master/Assets/Scripts/General/LevelLogic.cs) or function that adds a fade in and fade out everytime you load a new scene._

**Comment by Adri102** [comment]
Added the fade ins and fade outs

**Comment by Adri102** [comment]
Implemented in commit https://github.com/RobertFont/AlphaProject/commit/ba74552d33d741768af59986341f87a86a19a9c8
