### ISSUE TITLE
Create Alpha Games Logo Animation

### ISSUE THREAD

**Issue by CristianLuzon** [RobertFont/AlphaProject#29]
Create the logo animation of our team (Alpha Games). 
Implement a fade in / fade out animation that shows Alpha Games.

**EXPECTED RESULT:**

_Logo of Alpha Games implemented and animated at the beggining of the game, with a fade in / fade out animation._

**Comment by RobertFont** [comment]
The logo has already been added to github.

**Comment by CristianLuzon** [comment]
Implemented in commit (https://github.com/RobertFont/AlphaProject/commit/f00c28536ee97c18df8dd5f15aa0d8190f57745b)
