### ISSUE TITLE
Create A Resource Manager

### ISSUE THREAD

**Issue by KoroBli** [RobertFont/AlphaProject#3]
Create a resource manager that controls resources, it needs methods to add and remove every resource in the gameplay.

**EXPECTED RESULT:**

_A [resource manager](https://github.com/RobertFont/AlphaProject/blob/master/Assets/Scripts/Resources/ResourceManager.cs) script providing all the variables and methods to add and remove._

**Comment by CristianLuzon** [comment]
Implemented in commit https://github.com/RobertFont/AlphaProject/commit/e8ce4ea07af487222becbfbd48a649c18da28241
