### ISSUE TITLE
Create Title Entrance Animation

### ISSUE THREAD

**Issue by CristianLuzon** [RobertFont/AlphaProject#31]
Implement the entrance animation, of the game's logo. The logo has to appear from the top side of the screen and lower it's position until it reaches the final position.

**EXPECTED RESULT:**

_The title must have it's own animation made with [TitleBehaviour](https://github.com/RobertFont/AlphaProject/blob/master/Assets/Scripts/TitleBehaviour.cs)._

**Comment by Adri102** [comment]
Implemented in commit (https://github.com/RobertFont/AlphaProject/commit/f00c28536ee97c18df8dd5f15aa0d8190f57745b)

**Comment by KoroBli** [comment]
Reimplemented in commit: https://github.com/RobertFont/AlphaProject/commit/efe142855d80f1209f672205776f6d1a0c95f555
