### ISSUE TITLE
Implement The Final Buildings Models

### ISSUE THREAD

**Issue by CristianLuzon** [RobertFont/AlphaProject#36]
Implement the final models of 3 different buildings
- [X] TownHall
- [X] House
- [X] Farm

**EXPECTED RESULT**

_The final .fbx of the buildings implemented in the unity scene, [Farm](https://github.com/RobertFont/AlphaProject/blob/master/Assets/Models/Farm02.fbx), [House](https://github.com/RobertFont/AlphaProject/blob/master/Assets/Models/House01.fbx), [TownHall](https://github.com/RobertFont/AlphaProject/blob/master/Assets/Models/TownHall02.fbx)._

**Comment by RobertFont** [comment]
Deleted Issues because we already have another issues called "Create 3D Models Building" that says the same thing.

**Comment by Adri102** [comment]
Implented in commits https://github.com/RobertFont/AlphaProject/commit/886f58d99e9fa0b06a42bb735fff6e8a7f061a46 and https://github.com/RobertFont/AlphaProject/commit/173bc55c3e2a392e23d5fd7c889f170ba6063320
