### ISSUE TITLE
Implement The Basic UI Elements

### ISSUE THREAD

**Issue by CristianLuzon** [RobertFont/AlphaProject#38]
Create a functional Ui in-game elements with temporal Art. The Ui must give feedback when the player builds or destroy a building, and when the peasants gather resources

**EXPECTED RESULT:**

_A Ui that works with a script, [UiTrigger.cs](https://github.com/RobertFont/AlphaProject/blob/master/Assets/Scripts/General/UiTrigger.cs), and gives feedback to the player._

**Comment by Adri102** [comment]
Implemented in commit https://github.com/RobertFont/AlphaProject/commit/44551ad86b360f9389f8256bec647a834cc045a9
