### ISSUE TITLE
Implement Diferent Particle Sytems

### ISSUE THREAD

**Issue by CristianLuzon** [RobertFont/AlphaProject#39]
Create a 5 particle system to implement in the game. The particles must be descriptive, they need to show what they're doing.
- [X] Bugs
- [x] Smoke
- [X] Fire
- [X] Dust
- [X] Rain

**EXPECTED RESULTS:**

_The particles must be informative and produce the effect wanted. They must not interfere with the gameplay, unless it is meant to be done._

**Comment by KoroBli** [comment]
Current Particle Systems(Not implemented):
- Dust
- Fire(Implemented)
- Rain
- Illness Cloud
- Bugs

**Comment by KoroBli** [comment]
Last PS implemented in commit: https://github.com/RobertFont/AlphaProject/commit/8f96886aecf4768d8acb49547236d843268e8e9c
