### ISSUE TITLE
Implement The Construction Costs

### ISSUE THREAD

**Issue by KoroBli** [RobertFont/AlphaProject#4]
Create a cost manager method that change the resources when a building is contructed. If there is not enough resources to build the selected building, it can't be constructed.

**EXPECTED RESULT:**

_A cost manager methon in [builder script](https://github.com/RobertFont/AlphaProject/blob/master/Assets/Scripts/Buildings/BuilderScript.cs) that controls all building costs._

**Comment by Adri102** [comment]
Implemented in commit https://github.com/RobertFont/AlphaProject/commit/999d5504efd0fd8a73e411037e9e212b5916f3a8
