### ISSUE TITLE
Implement Diferent Sound FX

### ISSUE THREAD

**Issue by CristianLuzon** [RobertFont/AlphaProject#40]
Implement 5 sound FX to the gameplay. The sounds must be clearly hearable, and not ruin the gameplay, because of loudness.

- [x] Bugs
- [x] Fire
- [X] Music
- [X] Rain
- [x] Birds

**EXPECTED RESULTS:**

_Five files with different sounds that are played when their methods are launched_

**Comment by KoroBli** [comment]
Current Sounds(Not implemented):
- Bugs
- Fire
- Illness Plague
- Sickness
- Birds
- Scammers
- Thieves
- Barbarians

**Comment by CristianLuzon** [comment]
Implemented in commit (https://github.com/RobertFont/AlphaProject/commit/2e018c3f4cb8fd8d47db3130f3964a6978235b3f)

**Comment by KoroBli** [comment]
Reimplemented in commit: https://github.com/RobertFont/AlphaProject/commit/2e018c3f4cb8fd8d47db3130f3964a6978235b3f
