### ISSUE TITLE
Implement Building Basic Mecanics 

### ISSUE THREAD

**Issue by CristianLuzon** [RobertFont/AlphaProject#43]
Implement the building mechanic for all the different buildings, you can't build on another building, and it remove the resources equal to the cost of the building.

**EXPECTED RESULT:**

_A functional script, [BuilderScript.cs](https://github.com/RobertFont/AlphaProject/blob/master/Assets/Scripts/Buildings/BuilderScript.cs) that can build and place the diferentes buildings on the map._

**Comment by Adri102** [comment]
Implemented in commit https://github.com/RobertFont/AlphaProject/commit/44551ad86b360f9389f8256bec647a834cc045a9
