### ISSUE TITLE
Implement Different Events Mechanics

### ISSUE THREAD

**Issue by CristianLuzon** [RobertFont/AlphaProject#46]
Program and test the diferents events that we can discover in the game.
The event must happen during the gameplay respecting the time limit and having its handicaps.

- [X] Fire
- [x] Bugs
- [x] Dust
- [x] Rain

**EXPECTED RESULT:**

_The events should work with a script, [EventBehaviour.cs](https://github.com/RobertFont/AlphaProject/blob/master/Assets/Scripts/Events/EventBehaviour.cs), this script should do everything related with the events._

**Comment by Adri102** [comment]
Implemented in commmit https://github.com/RobertFont/AlphaProject/commit/8f96886aecf4768d8acb49547236d843268e8e9c
