### ISSUE TITLE
Implement The Tree Generator

### ISSUE THREAD

**Issue by KoroBli** [RobertFont/AlphaProject#47]
Trees must be generated with a random scale and rotation every time you start a new game. This doesn't affect the gameplay at all.

**EXPECTED RESULT:**

_The trees should change the scale and the rotation, with a random range diferent for every tree. this should be a part of [TreeBehaviour.cs ](https://github.com/RobertFont/AlphaProject/blob/master/Assets/Scripts/Resources/TreeBehaviour.cs)_

            tree = this.transform;
            random = Random.Range(0.7f, 1.2f);
            treeSize = tree.localScale;
        
            treeSize = new Vector3(random, Random.Range(0.7f, 1.4f), random);
            treeRotation = new Vector3(0, Random.Range(0.0f, 360.0f), 0);

            tree.localScale = treeSize;
            tree.transform.Rotate(treeRotation);

**Comment by Adri102** [comment]
Implemented in commit https://github.com/RobertFont/AlphaProject/commit/a1f58dfbeae515117ac3aa69bfa64964d3ad91d8
