### ISSUE TITLE
Detect Raycast Colliding With Canvas

### ISSUE THREAD

**Issue by KoroBli** [RobertFont/AlphaProject#52]
Make the raycast collide with the canvas to make sure that the player can't select any building while the construction menu is active.

**EXPECTED RESULT:**

_A method that detects the canvas by raycasting, the bool canSelect must be false in that case._

InputManager.cs [line](https://github.com/RobertFont/AlphaProject/blob/master/Assets/Scripts/General/InputManager.cs#L112)

**Comment by CristianLuzon** [comment]
Implemente in commit https://github.com/RobertFont/AlphaProject/commit/d2c4e0650fdca05606c885ebdf97e27e986d2eb0
