### ISSUE TITLE
Set The Occlusion Culling Properly

### ISSUE THREAD

**Issue by KoroBli** [RobertFont/AlphaProject#53]
The occlusion culling must not render any object that is out of the camera render view. When the camera moves, the objects must be rendered when they enter the camera render field, and hide the ones that stay out of the field.

**EXPECTED RESULT:**

_Set the unity presets of the occlusion culling, change the option buttons to make the buildings and props disapear, but they must work._

**Comment by CristianLuzon** [comment]
Implemented in the scene with the final map in commit https://github.com/RobertFont/AlphaProject/commit/2567f3d0ea521934db07dd853dc53ca7878cb9eb
