### ISSUE TITLE
Add The New Map To The Game

### ISSUE THREAD

**Issue by KoroBli** [RobertFont/AlphaProject#54]
Implement the new map and make sure that everything works. replant all trees, and place all the mines and mountains in the game. The map is visual, it needs a mesh to calculate the collider.

**EXPECTED RESULT:**

_A mesh to make the colliders and a tileset to make the graphics._
[2D reference](https://raw.githubusercontent.com/RobertFont/AlphaProject/master/WikiResources/Map.png)

**Comment by CristianLuzon** [comment]
implemented in commit https://github.com/RobertFont/AlphaProject/commit/a8e85e43a9ce14bcd14815035fdef376c222dc2b
