### ISSUE TITLE
Change UI Placeholder To Final UI

### ISSUE THREAD

**Issue by KoroBli** [RobertFont/AlphaProject#6]
Change the Placeholder UI for the final one. 
Change  the placement of the descriptive elements on the screen. 

**EXPECTED RESULT:**

_Improve the overall quality of the interface for the game, aswell as changing the UI elements so that they make more sense and are visually easier to recognize._

**Comment by RobertFont** [comment]
Implemented in commit 5d6dcd6b64f602c6dae23d7128f9d66090407091 3ea62b922ccfb0881c779e9310ca8b24c2cd2028 c822a16ca1efbe154d73de96d88d98629fd4c3ea 10ec381e81e49f938937283aec6e8ac9950b4573
