### ISSUE TITLE
Create The Screen  Mockups

### ISSUE THREAD

**Issue by KoroBli** [RobertFont/AlphaProject#7]
Create all the different screen mockups that shows what we expect to get as final result for the gameplay and the title and menu options.

**EXPECTED RESULT:**

_The .png of the mockups_
- [Title](https://github.com/RobertFont/AlphaProject/blob/master/MockUp/MockupGameplay01.png)
- [Options](https://github.com/RobertFont/AlphaProject/blob/master/MockUp/MockupGameOptions.png)
- [Gameplay 1](https://github.com/RobertFont/AlphaProject/blob/master/MockUp/MockupGameplay01.png)
- [Gameplay 2](https://github.com/RobertFont/AlphaProject/blob/master/MockUp/MockupGameplay02.png)

**Comment by Adri102** [comment]
Implemented in commit https://github.com/RobertFont/AlphaProject/commit/3cf162a2e8d376f2d784e730a146a2ffb39de718
