### ISSUE TITLE
Create Title Menu Operative

### ISSUE THREAD

**Issue by KoroBli** [RobertFont/AlphaProject#9]
Create the title menu, with a Continue Game, New Game, Load Game, Options and Exit. The buttons that are requested in the alpha must work correctly and take the player to the desired option.

**EXPECTED RESULT:**

_A canvas that provides buttons that triggers methods in the  [Script](https://github.com/RobertFont/AlphaProject/blob/master/Assets/Scripts/Menus/TitleBehaviour.cs)._
![Sample](https://github.com/RobertFont/AlphaProject/blob/master/MockUp/MockupMenu01.png)

**Comment by RobertFont** [comment]
This is already done.

**Comment by KoroBli** [comment]
Implemented in comit: https://github.com/RobertFont/AlphaProject/commit/4459c981e7ed2b86b9fcad788b3ad31cec131874
